"""try to fix tables v6

Revision ID: 182cae057e2
Revises: 39ce092e0dc
Create Date: 2020-02-15 13:52:03.149216

"""

# revision identifiers, used by Alembic.
revision = '182cae057e2'
down_revision = '39ce092e0dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
