"""try to fix tables v2

Revision ID: 192fcca984e
Revises: 365fea69d1c
Create Date: 2020-02-15 13:31:05.694176

"""

# revision identifiers, used by Alembic.
revision = '192fcca984e'
down_revision = '365fea69d1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
