"""try to fix tables v10

Revision ID: 29db7d1b6ba
Revises: 5b5432b941
Create Date: 2020-02-15 13:55:35.855527

"""

# revision identifiers, used by Alembic.
revision = '29db7d1b6ba'
down_revision = '5b5432b941'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
