"""try to fix tables v3

Revision ID: 2dac023405a
Revises: 192fcca984e
Create Date: 2020-02-15 13:33:56.872385

"""

# revision identifiers, used by Alembic.
revision = '2dac023405a'
down_revision = '192fcca984e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
