"""try to fix tables

Revision ID: 365fea69d1c
Revises: 557f2fb92f5
Create Date: 2020-02-15 13:18:52.546158

"""

# revision identifiers, used by Alembic.
revision = '365fea69d1c'
down_revision = '557f2fb92f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
