"""change password to hash

Revision ID: 37d8b9a73c1
Revises: 47d1fb7fbeb
Create Date: 2020-02-15 15:05:12.850841

"""

# revision identifiers, used by Alembic.
revision = '37d8b9a73c1'
down_revision = '47d1fb7fbeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'hash')
    ### end Alembic commands ###
