"""try to fix tables v5

Revision ID: 39ce092e0dc
Revises: ef67a3cc28
Create Date: 2020-02-15 13:49:49.070459

"""

# revision identifiers, used by Alembic.
revision = '39ce092e0dc'
down_revision = 'ef67a3cc28'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
