"""try to fix tables v8

Revision ID: 41f7022a739
Revises: 11c2b11b636
Create Date: 2020-02-15 13:54:01.214379

"""

# revision identifiers, used by Alembic.
revision = '41f7022a739'
down_revision = '11c2b11b636'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
