"""try to fix tables v12

Revision ID: 47d1fb7fbeb
Revises: a11b4db1b
Create Date: 2020-02-15 13:56:50.133616

"""

# revision identifiers, used by Alembic.
revision = '47d1fb7fbeb'
down_revision = 'a11b4db1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
