"""add username to users

Revision ID: 557f2fb92f5
Revises: 23fe9dc6a30
Create Date: 2020-02-15 13:16:41.857486

"""

# revision identifiers, used by Alembic.
revision = '557f2fb92f5'
down_revision = '23fe9dc6a30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
