"""try to fix tables v9

Revision ID: 5b5432b941
Revises: 41f7022a739
Create Date: 2020-02-15 13:54:32.458117

"""

# revision identifiers, used by Alembic.
revision = '5b5432b941'
down_revision = '41f7022a739'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
