"""try to fix tables v11

Revision ID: a11b4db1b
Revises: 29db7d1b6ba
Create Date: 2020-02-15 13:56:00.517949

"""

# revision identifiers, used by Alembic.
revision = 'a11b4db1b'
down_revision = '29db7d1b6ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
