"""try to fix tables v4

Revision ID: ef67a3cc28
Revises: 2dac023405a
Create Date: 2020-02-15 13:44:13.733342

"""

# revision identifiers, used by Alembic.
revision = 'ef67a3cc28'
down_revision = '2dac023405a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
